SELECT * FROM EMPLOYEES;

--rename colum
SELECT FIRST_NAME as given_name FROM EMPLOYEES;

SELECT MAX(SALARY) AS highest_salary FROM EMPLOYEES;

--another way rename-with"" i can remove _ from given name
SELECT FIRST_NAME as "given name" FROM EMPLOYEES;

--concat in java +

--IN SQL         //  WE NEED TO USE ALSO FOR CONCAT' '
--add email to @gmail.com domain
SELECT EMAIL||'@GMAIL.COM' AS FULL_EMAIL FROM EMPLOYEES;
SELECT CONCAT(EMAIL,'@gmail.COM') FROM EMPLOYEES;

--LOWER
SELECT LOWER(CONCAT(EMAIL,'@gmail.COM')) FROM EMPLOYEES;

--UPPER
SELECT UPPER(CONCAT(EMAIL,'@gmail.COM')) FROM EMPLOYEES;

--INITCAP  IT MAKES FIRST LETTER UPPERCASE
SELECT EMAIL FROM EMPLOYEES;
SELECT INITCAP(EMAIL) FROM EMPLOYEES;

----LENGTH
SELECT LENGTH(EMAIL) FROM EMPLOYEES;

SELECT FIRST_NAME,LENGTH(FIRST_NAME) AS length_firstName FROM EMPLOYEES
ORDER BY length_firstName;


--SUBSTR(col_name, beginIndex, numberOfChar)
SELECT SUBSTR(FIRST_NAME,0,1)||'.'||SUBSTR(LAST_NAME,0,1)||'.' FROM EMPLOYEES;
SELECT SUBSTR(FIRST_NAME,1,1)||'.'||SUBSTR(LAST_NAME,1,1)||'.' FROM EMPLOYEES;--SAME



-- INTERVIEW TASK
SELECT FIRST_NAME,SALARY FROM EMPLOYEES
WHERE SALARY>3000
ORDER BY LOWER(SUBSTR(FIRST_NAME,-3)) ASC,SALARY DESC;

SELECT LOWER(SUBSTR(FIRST_NAME,-3)) FROM EMPLOYEES
ORDER BY 1;







