SELECT * FROM ADDRESS;
SELECT * FROM CUSTOMER;


/*
 INNER JOIN
 ONLY MATCHING PORTIONS OF THE TABLE
 */
SELECT FIRST_NAME, LAST_NAME, ADDRESS, PHONE FROM CUSTOMER
INNER JOIN ADDRESS ON CUSTOMER.ADDRESS_ID = ADDRESS.ADDRESS_ID;


SELECT FIRST_NAME, LAST_NAME, ADDRESS.ADDRESS_ID,ADDRESS, PHONE
FROM CUSTOMER INNER JOIN ADDRESS ON CUSTOMER.ADDRESS_ID = ADDRESS.ADDRESS_ID

--ALIASES
SELECT FIRST_NAME, LAST_NAME, A.ADDRESS_ID,ADDRESS, PHONE
FROM CUSTOMER C INNER JOIN ADDRESS A ON C.ADDRESS_ID = A.ADDRESS_ID;

--LEFT OUTER MATCHING PART+ ONLY UNIQUE FOR LEFT TABLE.
SELECT FIRST_NAME, LAST_NAME, A.ADDRESS_ID,ADDRESS, PHONE
FROM CUSTOMER C left outer JOIN ADDRESS A ON C.ADDRESS_ID = A.ADDRESS_ID;

SELECT FIRST_NAME, LAST_NAME, A.ADDRESS_ID,ADDRESS, PHONE
FROM CUSTOMER C right outer join ADDRESS A ON C.ADDRESS_ID = A.ADDRESS_ID;

SELECT FIRST_NAME, LAST_NAME, A.ADDRESS_ID,ADDRESS, PHONE
FROM CUSTOMER C full join ADDRESS A ON C.ADDRESS_ID = A.ADDRESS_ID;


