SELECT * from employees;

--Average salary for it Prog
SELECT AVG(SALARY),MIN(SALARY),SUM(SALARY),MAX(SALARY) FROM EMPLOYEES
WHERE JOB_ID='IT_PROG';

-- display average salary for sa_rep
SELECT AVG(SALARY),MIN(SALARY),SUM(SALARY),MAX(SALARY) FROM EMPLOYEES
WHERE JOB_ID='SA_REP';

-- display average salary for MK_MAN
SELECT AVG(SALARY),MIN(SALARY),SUM(SALARY),MAX(SALARY) FROM EMPLOYEES
WHERE JOB_ID='MK_MAN';

SELECT JOB_ID,AVG(SALARY) FROM EMPLOYEES
GROUP BY JOB_ID;

SELECT JOB_ID,AVG(SALARY),MIN(SALARY),SUM(SALARY),MAX(SALARY),COUNT(*) FROM EMPLOYEES
GROUP BY JOB_ID;

--GET ME SALARY EACH DEP IN EMPLOYEES TABLE
SELECT DEPARTMENT_ID,JOB_ID,SUM(SALARY),COUNT(*)FROM EMPLOYEES
WHERE DEPARTMENT_ID IS NOT NULL
GROUP BY DEPARTMENT_ID,JOB_ID
ORDER BY DEPARTMENT_ID;

