/*
 MULTI-ROW / AGGREGATE / GROUPING FUNC
 count
 max
 min
 avg
 sum

 it will take multiple row and gives single output
 */
-- HOW MANY DEPARTMENTS DO WE HAVE
SELECT COUNT(*) FROM DEPARTMENTS;

-- HOW MANY DIFFERENT NAME DO WE HAVE
SELECT COUNT(DISTINCT FIRST_NAME) FROM EMPLOYEES;

-- HOW MANY EMPLOYEES WE HAVE WORKS AS IT PROGRAMER OR SALES REP
SELECT COUNT(*) FROM EMPLOYEES
WHERE JOB_ID IN ('IT_PROG','SA_REP');

-- HOW MANY EMPLOYEES WE HAVE AS DEPARTMENT ID IS NULL
SELECT COUNT(*) FROM EMPLOYEES
WHERE DEPARTMENT_ID IS NULL ;
-- IF THE VALUE IS NULL IT WILL NOT COUNT IT AND WILL GIVE US WRONG NUMBER

SELECT COUNT(DEPARTMENT_ID) FROM EMPLOYEES
WHERE DEPARTMENT_ID IS NOT NULL;

--GET MAX SALARY FROM EMPLOYEES
SELECT MAX(SALARY) FROM EMPLOYEES;

--GET MIN SALARY FROM EMPLOYEES
SELECT MIN(SALARY) FROM EMPLOYEES;

--GET TOTAL(SUM) SALARY FROM EMPLOYEES
SELECT SUM(SALARY) FROM EMPLOYEES;

--GET AVERAGE(AVG) SALARY FROM EMPLOYEES
SELECT AVG(SALARY) FROM EMPLOYEES;

--GET ROUND AVERAGE(AVG) SALARY FROM EMPLOYEES
SELECT ROUND(AVG(SALARY)) FROM EMPLOYEES;

--GET ROUND AVERAGE(AVG) SALARY FROM EMPLOYEES--(_,__)
SELECT ROUND(AVG(SALARY),2) FROM EMPLOYEES;
SELECT ROUND(AVG(SALARY),1) FROM EMPLOYEES;
SELECT ROUND(AVG(SALARY),3) FROM EMPLOYEES;
