SELECT * FROM EMPLOYEES
WHERE ROWNUM<=9;

-- WORKS WITH < AND <=

--DISPLAY INFO FOR 5 HIGHEST SALARY
--BAD AND WRONG PRACTISE
--GETS THE DATA WITHOUT ORDER AND GIVES FALSE RESULT
SELECT * FROM EMPLOYEES
WHERE ROWNUM<=5
ORDER BY SALARY DESC ;