SELECT * FROM EMPLOYEES
WHERE ROWNUM<=9;

-- WORKS WITH < AND <=

--DISPLAY INFO FOR 5 HIGHEST SALARY
--BAD AND WRONG PRACTISE
--GETS THE DATA WITHOUT ORDER AND GIVES FALSE RESULT
SELECT * FROM EMPLOYEES
WHERE ROWNUM<=5
ORDER BY SALARY DESC ;

SELECT * FROM (SELECT * FROM EMPLOYEES ORDER BY SALARY DESC )
WHERE ROWNUM<=5;


-- DISPLAY ALL INFO WHO IS GET-ING FIFTH HIGHEST SALARY
SELECT MIN(SALARY) FROM (SELECT DISTINCT SALARY FROM EMPLOYEES ORDER BY SALARY DESC )
WHERE ROWNUM<6;

-- DISPLAY ALL INFO WHO IS GET-ING 16 HIGHEST SALARY
SELECT MIN(SALARY) FROM (SELECT DISTINCT SALARY FROM EMPLOYEES ORDER BY SALARY DESC )
WHERE ROWNUM<16;

-- DISPLAY ALL INFO WHO IS GET-ING 213TH SALARY
SELECT MIN(SALARY) FROM (SELECT DISTINCT SALARY FROM EMPLOYEES ORDER BY SALARY DESC )
WHERE ROWNUM<214;

-- DISPLAY ALL INFO WHO IS GET-ING 5TH SALARY
SELECT * FROM EMPLOYEES
WHERE SALARY=(SELECT MIN(SALARY) FROM (SELECT DISTINCT SALARY FROM EMPLOYEES ORDER BY SALARY DESC )
              WHERE ROWNUM<6);
