
--REMOVES DUPLICATES FROM YOUR REQUESTED RESULT
-- ONLY FIRST_NAME FROM EMPLOYEES TABLE
SELECT FIRST_NAME FROM EMPLOYEES;
--GET ALL UNIQUE FIRST NAME FROM EMPLOYEES
SELECT DISTINCT FIRST_NAME FROM EMPLOYEES;

--GET UNIQUE JOB ID FROM EMPLOYEES
SELECT DISTINCT JOB_ID FROM EMPLOYEES;

--GET UNIQUE COUNTRY ID FROM LOCATIONS
SELECT DISTINCT COUNTRY_ID FROM LOCATIONS;