select * from employees;


SELECT *FROM EMPLOYEES;

SELECT *FROM DEPARTMENTS;

-- ONLY FIRST_NAME FROM EMPLOYEES TABLE
SELECT FIRST_NAME FROM EMPLOYEES;

--CITY NAMES FROM LOCATIONS TABLE
SELECT CITY FROM LOCATIONS;

-- FIRST_NAME, LAST NAME, SALARY FROM EMPLOYEES TABLE
SELECT FIRST_NAME,LAST_NAME,SALARY FROM EMPLOYEES;

--COUNTRY NAME,REGION ID FROM COUNTRIES
SELECT COUNTRY_NAME,REGION_ID FROM COUNTRIES;

--JOB ID, JOB TITLE FROM JOB TABLE
SELECT JOB_ID,JOB_TITLE FROM JOBS;

--STREET ADDRESS, POSTAL CODE FROM LOCATIONS
SELECT STREET_ADDRESS,POSTAL_CODE FROM LOCATIONS;
