
--WHERE IS USER FOR FILTERING

-- FIRST NAME, LAST NAME, SALARY FROM EMPLOYEES TABLE WHERE FIRST NAME IS DAVID
SELECT FIRST_NAME,LAST_NAME,SALARY FROM EMPLOYEES
WHERE FIRST_NAME='David';

-- '' inside we can use case sensitive data

-- FIRST NAME, LAST NAME, SALARY FROM EMPLOYEES TABLE WHERE FIRST NAME IS DAVID LAST MANE IS LEE
SELECT FIRST_NAME,LAST_NAME,SALARY FROM EMPLOYEES
WHERE FIRST_NAME='David'AND LAST_NAME='Lee';

--from employees who is making salary more than 6000
SELECT FIRST_NAME,LAST_NAME,SALARY FROM EMPLOYEES
WHERE SALARY>6000;

--all information from employees who is making salary equal or less than 6000
SELECT * FROM EMPLOYEES
WHERE SALARY<=6000;

--first name, salary from employees who is making salary more than 6000 department id =80
SELECT FIRST_NAME,SALARY FROM EMPLOYEES
WHERE SALARY>6000 and DEPARTMENT_ID=80;

SELECT FIRST_NAME,SALARY FROM EMPLOYEES
WHERE SALARY<=6000 and SALARY>=3000;
--Between lower and upper
SELECT FIRST_NAME,SALARY FROM EMPLOYEES
WHERE SALARY between 3000 and 6000;
--both included

-- who is working as a SA_REP and IT_PROG
SELECT * FROM EMPLOYEES
WHERE JOB_ID='SA_REP' OR JOB_ID='IT_PROG';

-- IN CLAUSES
--IT USE OR LOGIC
-- who is working as a SA_REP, FI_MGR and IT_PROG
SELECT * FROM EMPLOYEES
WHERE JOB_ID IN ('SA_REP','IT_PROG','FI_MGR');

-- who is NOT working as a SA_REP, FI_MGR and IT_PROG
SELECT * FROM EMPLOYEES
WHERE JOB_ID NOT IN ('SA_REP','IT_PROG','FI_MGR');


SELECT * FROM LOCATIONS
WHERE CITY IN ('Tokio', 'Roma');

-- from employees where id is = 113, 145, 124 ,122
SELECT * FROM EMPLOYEES
WHERE EMPLOYEE_ID IN (113,145,124,122);

--NULL AND NOT NULL
SELECT * FROM EMPLOYEES
WHERE DEPARTMENT_ID IS NULL;

SELECT * FROM EMPLOYEES
WHERE DEPARTMENT_ID IS NOT NULL;




